export const projectId = "drksmlvmfmuebcwfduys"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRya3NtbHZtZm11ZWJjd2ZkdXlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA0MDM2NTgsImV4cCI6MjA4NTk3OTY1OH0.wscVt5uej_xgK0QcarSQbBSzr0jJm4-1IZVGXTGEfrk"
